apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webook-mysql-pvc
spec:
  storageClassName: record
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      #      需要1G容量
      storage: 1Gi